import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";

export const Route = createFileRoute("/docs/$datasetId")({
  head: () => ({
    meta: [
      { title: "API Reference · Gridwire" },
      { name: "description", content: "Interactive OpenAPI reference for this dataset, generated by Gridwire." },
    ],
  }),
  component: DocsPage,
});

const SWAGGER_VERSION = "5.17.14";

function DocsPage() {
  const { datasetId } = Route.useParams();
  const containerRef = useRef<HTMLDivElement>(null);
  const [status, setStatus] = useState<"loading" | "ready" | "error">("loading");

  useEffect(() => {
    let cancelled = false;

    function loadCss() {
      if (document.getElementById("swagger-ui-css")) return;
      const link = document.createElement("link");
      link.id = "swagger-ui-css";
      link.rel = "stylesheet";
      link.href = `https://unpkg.com/swagger-ui-dist@${SWAGGER_VERSION}/swagger-ui.css`;
      document.head.appendChild(link);
    }

    function loadScript(): Promise<void> {
      return new Promise((resolve, reject) => {
        if ((window as unknown as { SwaggerUIBundle?: unknown }).SwaggerUIBundle) return resolve();
        const script = document.createElement("script");
        script.src = `https://unpkg.com/swagger-ui-dist@${SWAGGER_VERSION}/swagger-ui-bundle.js`;
        script.crossOrigin = "anonymous";
        script.onload = () => resolve();
        script.onerror = () => reject(new Error("Failed to load Swagger UI"));
        document.body.appendChild(script);
      });
    }

    (async () => {
      try {
        loadCss();
        await loadScript();
        if (cancelled || !containerRef.current) return;
        const SwaggerUIBundle = (window as unknown as { SwaggerUIBundle: (o: unknown) => void }).SwaggerUIBundle;
        SwaggerUIBundle({
          url: `/api/v1/datasets/${datasetId}/openapi.json`,
          domNode: containerRef.current,
          deepLinking: true,
          persistAuthorization: true,
          tryItOutEnabled: true,
        });
        setStatus("ready");
      } catch {
        if (!cancelled) setStatus("error");
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [datasetId]);

  return (
    <div style={{ minHeight: "100vh", background: "#fff" }}>
      {status === "loading" && (
        <div style={{ padding: "2rem", fontFamily: "system-ui, sans-serif", color: "#555" }}>
          Loading API reference…
        </div>
      )}
      {status === "error" && (
        <div style={{ padding: "2rem", fontFamily: "system-ui, sans-serif", color: "#b00020" }}>
          Could not load the API reference. The dataset may be unpublished, or the spec is at{" "}
          <code>/api/v1/datasets/{datasetId}/openapi.json</code>.
        </div>
      )}
      <div ref={containerRef} />
    </div>
  );
}
